#!/bin/bash

set -e

echo "Running pre commit script"

cd "$(git rev-parse --show-toplevel)"

./enrich-topics.sh
./bundle.sh

# Re-add any changed files to staging area
git add topics
git add .bundles

# Allow the commit to proceed
exit 0
